name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: "/root/go/pkg/github.com/raghavgg/gms-frontend"

      - name: Building production build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /root/go/pkg/github.com/raghavgg/gms-frontend
            yarn build
            cp -r dist/* /var/www/html/app.supremegms.com/
            rm -rf /root/go/pkg/github.com/raghavgg/gms-frontend/*

      - name: Moving content to apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /root/go/pkg/github.com/raghavgg/gms-frontend
            cp -r dist/* /var/www/html/app.supremegms.com/
            rm -rf /root/go/pkg/github.com/raghavgg/gms-frontend/*

      - name: Deleting content of repo content
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: rm -rf /root/go/pkg/github.com/raghavgg/gms-frontend/*
